name: Pull Request

on: pull_request

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libx11-dev libxrandr-dev libxi-dev libxcursor-dev libudev-dev libgl1-mesa-dev freeglut3-dev libfreetype-dev libogg-dev libvorbis-dev libflac-dev
      - name: Build SFML
        run: |
          gh repo clone SFML/SFML
          cd SFML
          git checkout 3.0.1
          mkdir build
          cd build
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release ..
          make -j
          cp lib/*.a ../../lib/linux/
      - name: CMake build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j
